add ipex quicktour
huggingface/optimum pull request #2014
Opened 2024-09-04 01:23 UTC by jiqing-feng

Add ipex quicktour

2024-09-04 01:36 UTC, sywangyi approved these changes

2024-09-04 01:41 UTC, jiqing-feng commented
Hi @echarlaix @IlyasMoutawwakil . Could you please review this PR since ipex doc has been enabled in optimum-intel doc.

2024-09-04 16:20 UTC, echarlaix requested changes
Waiting for the IPEX refactorization (once model exported via TorchScript are officially deprecated) + next optimum-intel release before can be merged

2024-09-04 16:31 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum/pr_2014). All of your documentation changes will be reflected on that endpoint. The docs are available until 30 days after the last update.

2024-09-09 04:38 UTC, jiqing-feng commented
> Thanks for the PR @jiqing-feng ! Waiting for the IPEX refactorization (once model exported via TorchScript are officially deprecated) + next optimum-intel release before can be merged

Hi @echarlaix . For now, torch.compile is not ready yet. It's hard to give a deadline for torch.compile ready. We can not block everything by it. 
Beaised, I have noticed torch.compile in the document.

2024-09-13 07:23 UTC, closed without merging