Added image-to-image task for ORT Pipeline
huggingface/optimum pull request #2031
Opened 2024-09-19 23:44 UTC by h3110Fr13nd

# What does this PR do?

Fixes #2030
Image To Image task consist lot more than Diffusion and there are transformer based model such as Swin. 
This PR adds the support for pielining image-to-image task with ORTModelForImage2Image.
e.g.
```python
from transformers import AutoImageProcessor
from optimum.pipelines import pipeline
from optimum.onnxruntime import ORTModelForImageToImage
from PIL import Image

model = ORTModelForImageToImage.from_pretrained("swin2sr-2x-onnx", use_io_binding=True)
processor = AutoImageProcessor.from_pretrained("caidas/swin2SR-classical-sr-x2-64")
onnx = pipeline("image-to-image", model=model, feature_extractor=processor, device="cuda")
image_path = "image.png"
image = Image.open(image_path)
output = onnx(image)
```

## Before submitting
- [x] This PR fixes a typo or improves the docs (you can dismiss the other checks if that's the case).
- [ ] Did you make sure to update the documentation with your changes?
- [ ] Did you write any new necessary tests?

## Who can review?
@fxmarty, @echarlaix, @JingyaHuang, @michaelbenayoun

2024-09-20 10:02 UTC, IlyasMoutawwakil commented
awesome ! don't hesitate to ping me for review when it's ready !

2024-09-21 06:04 UTC, h3110Fr13nd commented
> awesome ! don't hesitate to ping me for review when it's ready !

Sure. Writing some tests. Will update you soon.

2024-09-23 22:16 UTC, h3110Fr13nd commented
Suggest Changes if Any.

2024-09-24 05:49 UTC, IlyasMoutawwakil commented on optimum/onnxruntime/__init__.py
> +from optimum.utils import is_diffusers_available
```suggestion
from ..utils import is_diffusers_available
```

2024-09-24 05:51 UTC, IlyasMoutawwakil commented on optimum/onnxruntime/modeling_ort.py
> +            processor_class=_PROCESSOR_FOR_IMAGE,
`_PROCESSOR_FOR_DOC="AutoProcessor"` should work as well here.

2024-09-24 05:55 UTC, IlyasMoutawwakil commented on tests/onnxruntime/test_modeling.py
> +        transformers_model = AutoModelForImageToImage.from_pretrained(model_id_transformer)
```suggestion
        model_id = MODEL_NAMES[model_arch]
        transformers_model = AutoModelForImageToImage.from_pretrained(model_id )
```

2024-09-24 05:55 UTC, IlyasMoutawwakil commented on tests/onnxruntime/test_modeling.py
> +        image_processor = self._get_preprocessors(model_id_transformer)
```suggestion
        image_processor = self._get_preprocessors(model_id )
```

2024-09-24 05:57 UTC, IlyasMoutawwakil commented on tests/onnxruntime/test_modeling.py
> +        onnx_model = ORTModelForImageToImage.from_pretrained(model_id)
you'll need to call self._setup here to export the model and save it.

2024-09-24 06:22 UTC, IlyasMoutawwakil commented on tests/onnxruntime/test_modeling.py
> +    def test_compare_to_transformers(self, test_name: str, model_arch: str, use_cache: bool, use_merged: bool):
no need for those arguments as they're specific for generative tasks
```suggestion
    @parameterized.expand(
        grid_parameters({"model_arch": SUPPORTED_ARCHITECTURES})
    )
    def test_compare_to_transformers(self, test_name: str, model_arch: str):
```

2024-09-24 06:24 UTC, IlyasMoutawwakil requested changes
Looks good, I left a few comments and suggestions, mostly to follow the same testing pipeline we have for other ORTModels:
- base the TestCase on a simpler task (I think u based on generative tasks)
- use setup to export/use an exported model
- use tiny models for faster testing

2024-09-24 07:11 UTC, IlyasMoutawwakil commented on optimum/pipelines/pipelines_base.py
> +            "default": "h3110Fr13nd/swin2sr-lightweight-2x-onnx",
should be the same default in transformers pipelines

2024-09-24 07:12 UTC, IlyasMoutawwakil commented on tests/onnxruntime/test_modeling.py
> +        onnx_model = ORTModelForImageToImage.from_pretrained(model_id, export=True)
once set up is done, you can load model with `ORTModelForImageToImage.from_pretrained(self.onnx_model_dirs[test_name])` to avoid re-export

2024-09-24 07:12 UTC, IlyasMoutawwakil commented on tests/onnxruntime/test_modeling.py
> +        onnx_model = ORTModelForImageToImage.from_pretrained(model_id, export=True)
```suggestion
        onnx_model = ORTModelForImageToImage.from_pretrained(self.onnx_model_dirs[test_name])
```

2024-09-24 07:15 UTC, IlyasMoutawwakil commented on tests/onnxruntime/test_modeling.py
> +        self._setup({"test_name": test_name, "model_arch": model_arch})
there's no test_name argument here
```suggestion
    def test_compare_to_transformers(self, model_arch: str):
        model_args = {"test_name": model_arch, "model_arch": model_arch}
        self._setup(model_args)
```

2024-09-24 10:06 UTC, IlyasMoutawwakil approved these changes
LGTM !
did you test io binding locally ?

2024-09-24 10:45 UTC, h3110Fr13nd commented
> LGTM ! did you test io binding locally ?

Yes.

2024-09-25 17:59 UTC, h3110Fr13nd commented
Should I add a test for that?

2024-09-26 07:29 UTC, IlyasMoutawwakil commented
we won't be able to test it until #2024 is re-enabled. will merge this now.

2024-09-26 07:29 UTC, merged