add mt5 to ORTConfigManager conf list
huggingface/optimum pull request #341
Opened 2022-08-09 11:40 UTC by ChainYo

# What does this PR do?

Add MT5 to `ORTConfigManager`.

Fixes #321 

I re-arranged in alphabetical order all available models. I can put it back like it was if needed. 🤗

@JingyaHuang

2022-08-09 12:18 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum/pr_341). All of your documentation changes will be reflected on that endpoint.

2022-08-10 13:06 UTC, JingyaHuang commented
Hi @ChainYo, thank you for adding mt5 in transformers and in optimum!

Sorting the models in alphabetical order makes sense to me. Can you also add a test of mt5 on `tests/onnxruntime/test_optimization.py` with the model `hf-internal-testing/tiny-random-mt5`? Thanks!

2022-08-10 14:22 UTC, ChainYo commented
Same as above, I re-arranged in alphabetical order all tested architectures.

Because `MT5` has no sequence-classification feature, I introduced a new argument: `model_feature`. Let me know if it's ok or not.
But it could help in the future with other models not designed for `sequence-classification`.

2022-08-10 14:24 UTC, ChainYo commented on tests/onnxruntime/test_optimization.py
> +    def test_optimize(self, model_cls, model_name, model_feature):
Here is the new `str` argument for the model feature.

2022-08-10 14:25 UTC, ChainYo commented on tests/onnxruntime/test_optimization.py
> +        (XLMRobertaForSequenceClassification, "hf-internal-testing/tiny-xlm-roberta", "sequence-classification"),
I added the `sequence-classification` feature for others and `seq2seq-lm` for the MT5 model.

2022-08-12 08:29 UTC, JingyaHuang reviewed
The refactoring looks neat to me, pinging @regisss and @michaelbenayoun for some inputs.

2022-08-12 08:32 UTC, regisss approved these changes
LGTM, thanks for this @ChainYo!!

2022-08-12 08:32 UTC, regisss commented
The build PR doc test should pass now

2022-08-12 08:34 UTC, regisss commented
As for opening an issue for implementing all available ONNX models in the ORTConfigManager, why not. IT could be a good way to track what models still have to be added. What do you think @JingyaHuang @echarlaix @mfuntowicz @fxmarty ?

2022-08-12 08:42 UTC, JingyaHuang commented
Besides, it seems that the CI of the optimization has one failed test:
```
2022-08-10T14:39:30.5123260Z =========================== short test summary info ============================
2022-08-10T14:39:30.5123701Z FAILED onnxruntime/test_optimization.py::ORTOptimizerTest::test_optimize_6 - ...
```
I can't see details about where it failed. Can you run the test locally to get the complete log of the failure? Thank you!

2022-08-12 08:48 UTC, JingyaHuang commented
> As for opening an issue for implementing all available ONNX models in the ORTConfigManager, why not. It could be a good way to track which models still have to be added. What do you think @JingyaHuang @echarlaix @mfuntowicz @fxmarty ?

IMO, it makes sense to keep them all in the test as far as it won't slow down the CI. When it turns to be too slow, we can archive a part of them as slow tests.

2022-08-12 08:54 UTC, regisss commented
> > As for opening an issue for implementing all available ONNX models in the ORTConfigManager, why not. It could be a good way to track which models still have to be added. What do you think @JingyaHuang @echarlaix @mfuntowicz @fxmarty ?
> 
> IMO, it makes sense to keep them all in the test as far as it won't slow down the CI. When it turns to be too slow, we can archive a part of them as slow tests.

I was actually talking about the suggestion of opening an issue such as [this one](https://github.com/huggingface/transformers/issues/16308) to keep track of the models to add to `ORTConfigManager`.

2022-08-12 09:20 UTC, JingyaHuang commented
@regisss oh sorry, I misunderstood it. I think that is a good idea! Both users and contributors could have a better idea about what has been integrated, what need to be integrated, and probably how to do that.

2022-08-12 09:39 UTC, regisss commented
> @regisss oh sorry, I misunderstood it. I think that is a good idea! Both users and contributors could have a better idea about what has been integrated, what needs to be integrated, and probably some references on how to do that.

Yes exactly :)

@ChainYo Feel free to create such an issue :+1:

2022-08-16 06:50 UTC, ChainYo commented
> > @regisss, oh sorry, I misunderstood it. I think that is a good idea! Both users and contributors could have a better idea about what has been integrated, what needs to be integrated, and probably some references on how to do that.
> 
> Yes exactly :)
> 
> @ChainYo Feel free to create such an issue +1

Cool, I will open it right now!

> Besides, it seems that the CI of the optimization has one failed test:
> 
> ```
> 2022-08-10T14:39:30.5123260Z =========================== short test summary info ============================
> 2022-08-10T14:39:30.5123701Z FAILED onnxruntime/test_optimization.py::ORTOptimizerTest::test_optimize_6 - ...
> ```
> 
> I can't see details about where it failed. Can you run the test locally to get the complete log of the failure? Thank you!

I will take a look at the failure message.

2022-08-22 07:55 UTC, JingyaHuang commented
Hi @ChainYo,

Thanks for explaining, that's clear. Indeed, as the CI leverages the latest transformers, it won't pass until your contribution of MT5 ONNX config makes its way to a release of transformers.

2022-08-24 14:26 UTC, customer101 commented
Hi @ChainYo,
I really appreciate the work done to support mT5 on optimum, this saves me a lot of time.
I have faced some issues after running this code :
```
model_path = "./mt5_model"
tokenizer = T5Tokenizer.from_pretrained(model_path)
model = ORTModelForSeq2SeqLM.from_pretrained(model_path, from_transformers=True)
```
it fails at `optimum/onnxruntime/modeling_seq2seq.py` :
```
        # Export the decoder with the past key values
        if use_cache:
            export(
                preprocessor=tokenizer,
                model=decoder_with_lm_head,
                config=onnx_config_decoder_with_past,
                opset=onnx_opset,
                output=save_dir.joinpath(ONNX_DECODER_WITH_PAST_NAME),
            )
```
Error:
```
RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 85 but got size 64 for tensor number 1 in the list.
```
If I set `use_cache=false`, it works fine. Does setting it to false will degrade the speed-up expected from onnx optimizations?

2022-08-25 07:50 UTC, ChainYo commented
> Hi @ChainYo, I really appreciate the work done to support mT5 on optimum, this saves me a lot of time. I have faced some issues after running this code :
> 
> ```
> model_path = "./mt5_model"
> tokenizer = T5Tokenizer.from_pretrained(model_path)
> model = ORTModelForSeq2SeqLM.from_pretrained(model_path, from_transformers=True)
> ```
> 
> it fails at `optimum/onnxruntime/modeling_seq2seq.py` :
> 
> ```
>         # Export the decoder with the past key values
>         if use_cache:
>             export(
>                 preprocessor=tokenizer,
>                 model=decoder_with_lm_head,
>                 config=onnx_config_decoder_with_past,
>                 opset=onnx_opset,
>                 output=save_dir.joinpath(ONNX_DECODER_WITH_PAST_NAME),
>             )
> ```
> 
> Error:
> 
> ```
> RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 85 but got size 64 for tensor number 1 in the list.
> ```
> 
> If I set `use_cache=false`, it works fine. Does setting it to false will degrade the speed-up expected from onnx optimizations?



> Hi @ChainYo, I really appreciate the work done to support mT5 on optimum, this saves me a lot of time. I have faced some issues after running this code :
> 
> ```
> model_path = "./mt5_model"
> tokenizer = T5Tokenizer.from_pretrained(model_path)
> model = ORTModelForSeq2SeqLM.from_pretrained(model_path, from_transformers=True)
> ```
> 
> it fails at `optimum/onnxruntime/modeling_seq2seq.py` :
> 
> ```
>         # Export the decoder with the past key values
>         if use_cache:
>             export(
>                 preprocessor=tokenizer,
>                 model=decoder_with_lm_head,
>                 config=onnx_config_decoder_with_past,
>                 opset=onnx_opset,
>                 output=save_dir.joinpath(ONNX_DECODER_WITH_PAST_NAME),
>             )
> ```
> 
> Error:
> 
> ```
> RuntimeError: Sizes of tensors must match except in dimension 2. Expected size 85 but got size 64 for tensor number 1 in the list.
> ```
> 
> If I set `use_cache=false`, it works fine. Does setting it to false will degrade the speed-up expected from onnx optimizations?

HI @customer101, could you check your model's `config.json` file and tell me the architecture used? Did you convert the MT5 model to ONNX with the main branch of Transformers?

Are you using it in a pipeline or with vanilla PyTorch? Where do you add the `use_cache=False` argument?

2022-08-25 12:38 UTC, customer101 commented
I used transformers main branch, the model is vanilla PyTorch,
this line:
```
model = ORTModelForSeq2SeqLM.from_pretrained(model_path, from_transformers=True, use_cache=False)
```
does the conversion, then when I save the model it dumps 2 onnx models(encoder and decoder).
Here is the `config.json`:
```
{
  "_name_or_path": "mt5_model",
  "architectures": [
    "MT5ForConditionalGeneration"
  ],
  "d_ff": 1024,
  "d_kv": 64,
  "d_model": 512,
  "decoder_start_token_id": 0,
  "dropout_rate": 0.1,
  "early_stopping": true,
  "eos_token_id": 1,
  "feed_forward_proj": "gated-gelu",
  "initializer_factor": 1.0,
  "is_encoder_decoder": true,
  "layer_norm_epsilon": 1e-06,
  "max_length": 256,
  "model_type": "mt5",
  "num_beams": 3,
  "num_decoder_layers": 8,
  "num_heads": 6,
  "num_layers": 8,
  "pad_token_id": 0,
  "relative_attention_num_buckets": 32,
  "tie_word_embeddings": false,
  "tokenizer_class": "T5Tokenizer",
  "torch_dtype": "float32",
  "transformers_version": "4.17.0",
  "use_cache": true,
  "vocab_size": 250112
}
```
I noticed that mt5 optimizations are not implemented yet in onnxruntime, so I think I won't gain much speed-up by converting to onnx.
Let me know if you need further information, good luck @ChainYo .

2022-09-15 07:43 UTC, ChainYo commented
HI @JingyaHuang @regisss 

Transformers v4.22.0 has included the MT5 OnnxConfig and stuff. Can we relaunch tests and see if all is fine here?

2022-09-15 08:14 UTC, JingyaHuang commented
Hi @ChainYo,

Sure, before launching the tests again, can you do a rebase with the main branch of Optimum? Thank you!

2022-09-15 08:41 UTC, ChainYo commented
> Sure, before launching the tests again, can you do a rebase with the main branch of Optimum? Thank you!

It's done @JingyaHuang

Optimizer behavior has changed, so adding a feature argument is not needed anymore!

2022-09-15 09:45 UTC, ChainYo commented
I fixed a typo for tests.

I don't know if `ORTModelForCustomTasks` is the best one, but I didn't find any `ORTModelForConditionalGeneration`. Or maybe I should import the MT5 specific one?

2022-09-15 14:16 UTC, JingyaHuang commented
Hi @ChainYo, the current `ORTModelForCustomTasks` doesn't support the sequence-to-sequence model yet, it shall be `ORTModelForSeq2SeqLM` in this case.

As @customer101 observes, for the moment, there is a problem with the dimension of past-key-value, so you need to set `use_cache=False` for the time being as a workaround. 

Here is the snippet:
```
from optimum.onnxruntime import ORTModelForSeq2SeqLM
model = ORTModelForSeq2SeqLM.from_pretrained("google/mt5-small", from_transformers=True, use_cache=False)
```

2022-09-15 14:29 UTC, JingyaHuang commented
Hi @customer101 ,

Thanks for reporting the issue with `use_past`. It seems that there is an issue while exporting decoder_with_past.

`past_key_values` contains pre-computed keys and values for attention which helps to speed up sequential decoding.  Can you open an separate issue concerning the bug, so that we can discuss and tackle it together?

2022-09-19 07:14 UTC, ChainYo commented
Hi @JingyaHuang,

I see there is two problems according to the error tests in the CI.
- First: about `evaluate`: 

```
ModuleNotFoundError: No module named 'evaluate'
```

- Second: about `mt5` KeyError

```

2022-09-20 15:26 UTC, JingyaHuang requested changes
Hi @ChainYo, 

Thanks for tracking the PR.

To pass the CIs, here are several modifications to apply:

* For the benchmark suite test, can you rebase your branch? The evaluate module has been added since #384 
* For the MT5 support, the name of hidden size shall be `d_model`.
* ONNX Runtime optimization supports bert-like, gpt-like and bart-like models. As t5/mt5 are encoder-decoder models, I suggest setting the model type as "bart" to benefit from [some extra fusions](https://github.com/microsoft/onnxruntime/blob/189aef2beaecdbdd3a68fbf569d9891c11d9777c/onnxruntime/python/tools/transformers/onnx_model_bart.py#L307-L308).
* And we recently reduced the size of some models to accelerate the CIs, can you use "hf-internal-testing/tiny-random-onnx-mt5" for the test?

With the modifications beyond, the PR should be good to go!

2022-10-02 11:12 UTC, JingyaHuang approved these changes

2022-10-02 12:05 UTC, JingyaHuang approved these changes
Thanks for iterating the PR, LGTM!

2022-10-02 12:05 UTC, merged