Do not force download by default in ORTModel
huggingface/optimum pull request #356
Opened 2022-08-23 10:51 UTC by fxmarty

We passed by default `force_download=True`, although the caching works well when passing `force_download=False`. Especially when passing `from_transformers=False`, everything works as expected as the onnx model is loaded from the cache `hub/` subfolder.

When passing `from_transformers=True`, although we cache only the PyTorch model (before [the new transformers cache system ](https://github.com/huggingface/transformers/pull/18438) in `transformers/` cache subfolder, in `hub/` subfolder in the next transformers release), the `force_download` argument is anyway ignored in `_from_transformers` so this PR has no impact there:

https://github.com/huggingface/optimum/blob/e90332463f7d2c1ae7e6feb93cfb379f92ed6231/optimum/onnxruntime/modeling_ort.py#L239-L303

2022-08-23 11:07 UTC, HuggingFaceDocBuilderDev commented
The docs for this PR live [here](https://moon-ci-docs.huggingface.co/docs/optimum/pr_356). All of your documentation changes will be reflected on that endpoint.

2022-08-23 11:27 UTC, regisss approved these changes
LGTM @fxmarty!

If the `force_download` argument is not used in `_from_transformers`, maybe we should remove it what do you think?

2022-08-23 12:35 UTC, philschmid requested changes
That's awesome! But we have to add test to validate that it is working as expected. Especially since we are storing the "model.onnx" files at the top level with out any hash. So there is no way for the library to know if the cached "model.onnx" is the correct one or not.

We can add the `local_files_only` argument to the from_pretrained method and have then working and failing tests for "cached" and regular models. As well as for loading different models after each other to make sure we have the correct ones loaded. 
See documentation: https://huggingface.co/docs/huggingface_hub/package_reference/file_download#huggingface_hub.hf_hub_download.local_files_only

We should also check that this works for the seq2seq models. 

And we should check if the new cache system allows better distribution of onnx files. Currently, when a user loads and saves a onnx file it is saved at the top cache directory with `model.onnx`, which means if he loads a new model "from" cache it uses the old model. Thats why i went with "force_download" in the beginning.

2022-08-23 12:58 UTC, fxmarty commented
When loading an onnx model with `from_transformers=False`, here's where it is loaded from in the `hub/` subfolder:

![image](https://user-images.githubusercontent.com/9808326/186160274-867483f1-ac4f-4df7-92ec-2b4e352c0d3f.png)

For seq2seq models (with `from_transformers=False`), we have:

![image](https://user-images.githubusercontent.com/9808326/186160943-5c7591fe-353c-4b47-8f96-730f43fdcec9.png)


which does work as well. Thanks for the suggestion to add tests, I will try to add some!

When `from_transformers=True`, the argument `force_download` is ignored. 

In case we passed `from_transformers=True`, in the old caching system, we indeed get e.g. a `transformers/facebook/levit-256/model.onnx` file with no hash recorded. However, even if this file exists, it is NOT loaded into the `InferenceSession` and the cached pytorch model is converted to onnx and loaded into an InferenceSession.

Under the new caching system, if we pass `from_transformers=True`, we get e.g. a `hub/facebook/levit-256/model.onnx` with no hash recorded as well. Looking at the timestamps, this file is overwritten at every conversion.

In any case, I think the case `from_transformers=True` is independent from this PR.

2022-08-24 05:53 UTC, philschmid approved these changes
LGTM!

2022-08-24 10:12 UTC, merged